{
  "hash": "494eb83ae6644f2599641cebf85a27d0",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"生産プロセス\"\nauthor: \"Serika Yuzuki\"\ndate: \"2024-12-17\"\ncategories: [University, 2024]\nimage: \"images/thumbnail.png\"\n---\n\n\n\n\n$$\n\\require{physics}\n\\require{mhchem}\n\\require{ams}\n$$\n\n# レポート課題\n\nStandard Gibss free energy のまとめ。\n\n|Compounds|$\\Delta G\\  \\text{KJ}\\ \\text{mol}^{-1}$|\n|---|---|\n|Ba(s)|0|\n|BaO(s)|-520.40592|\n|BaS(s)|-456.056|\n|BaSO4(s)|-1362.3104|\n|O2(g)|0|\n|S2(g)|80.08176|\n\n::: {#63736d24 .cell execution_count=1}\n``` {.python .cell-code}\nimport numpy as np\n\ndelta_G1 = -520.40592  # Ba(s) -> BaO(s)\ndelta_G2 = -456.056-(80.08176/2)   # Ba(s) -> BaS(s)\ndelta_G3 = -1362.3104-(80.08176/2)  # Ba(s) -> BaSO4(s)\ndelta_G4 = -1362.3104+520.40592-(80.08176/2)  # BaO(s) -> BaSO4(s)\ndelta_G5 = -1362.3104+456.056  # BaS(s) -> BaSO4(s)\ndelta_G6 = -520.40592+(80.08176/2)+456.056  # BaS(s) -> BaO(s) + S2(g)\n\ndelta_G1, delta_G2, delta_G3, delta_G4, delta_G5, delta_G6\n```\n\n::: {.cell-output .cell-output-display execution_count=3}\n```\n(-520.40592,\n -496.09688,\n -1402.35128,\n -881.94536,\n -906.2544,\n -24.30904000000004)\n```\n:::\n:::\n\n\n$$\n\\begin{aligned}\n& \\ce{Ba(s) + 1/2 O2(g) -> BaO(s)} \\quad \\Delta G_1 = -520.406\\ \\text{KJ mol}^{-1} \\\\\n& \\ce{Ba(s) + 1/2 S2(g) -> BaS(s)} \\quad \\Delta G_2 = -496.097\\ \\text{KJ mol}^{-1} \\\\\n& \\ce{Ba(s) + 1/2 S2(g) + 2O2(g) -> BaSO4(s)} \\quad \\Delta G_3 = -1402.35\\ \\text{KJ mol}^{-1} \\\\\n& \\ce{BaO(s) + 1/2 S2(g) + \\frac{3}{2}O2(g) -> BaSO4(s)} \\quad \\Delta G_4 = -881.945\\ \\text{KJ mol}^{-1} \\\\\n& \\ce{BaS(s) + 2O2 -> BaSO4(s)} \\quad \\Delta G_5 = -906.254\\ \\text{KJ mol}^{-1} \\\\\n& \\ce{BaS(s) + \\frac{1}{2}O2 -> BaO(s) + \\frac{1}{2}S2(g)} \\quad \\Delta G_6 = -24.3090\\ \\text{KJ mol}^{-1} \\\\\n\\end{aligned}\n$$\n\n$$\n\\begin{aligned}\n\\frac{G_1}{RT} &= \\frac{1}{2}\\log P_{\\ce{O_2}} \\\\\n\\frac{G_2}{RT} &= \\frac{1}{2}\\log P_{\\ce{S_2}} \\\\\n\\frac{G_3}{RT} &= \\frac{1}{2}\\log P_{\\ce{S_2}} + 2\\log P_{\\ce{O_2}} \\\\\n\\frac{G_4}{RT} &= \\frac{1}{2}\\log P_{\\ce{S_2}} + \\frac{3}{2}\\log P_{\\ce{O_2}} \\\\\n\\frac{G_5}{RT} &= 2\\log P_{\\ce{O_2}} \\\\\n\\frac{G_6}{RT} &= \\frac{1}{2}\\log P_{\\ce{O_2}} - \\frac{1}{2}\\log P_{\\ce{S_2}} \\\\\n\\end{aligned}\n$$\n\n::: {#3c31dde3 .cell execution_count=2}\n``` {.python .cell-code}\nimport numpy as np\nimport matplotlib.pyplot as plt\n\n# 定数設定\nR = 8.314  # 気体定数 (J/(mol*K))\nT = 900    # 温度 (K)\n\n# ギブズ自由エネルギー変化 (J/mol)\ndelta_G1 = -520.406 * 1e3  # Ba -> BaO\ndelta_G2 = -496.097 * 1e3  # Ba -> BaS\ndelta_G3 = -1402.35 * 1e3  # Ba -> BaSO4\ndelta_G4 = -881.945 * 1e3  # BaO -> BaSO4\ndelta_G5 = -906.254 * 1e3  # BaS -> BaSO4\ndelta_G6 = -24.3090 * 1e3  # BaS -> BaO + S2\n\n# 直線の描画\n# y = log_PO2, x = log_PS2\n\n# Ba -> BaO\nx = np.linspace(-150, 0, 500)\nlog_PO2 = 2 * delta_G1 / (R * T)\ny = np.full_like(x, log_PO2)\n\nplt.plot(x, y, label='Ba -> BaO')\n\n# Ba -> BaS\ny = np.linspace(-150, 0, 500)\nlog_PS2 = 2 * delta_G2 / (R * T)\nx = np.full_like(y, log_PS2)\n\nplt.plot(x, y, label='Ba -> BaS')\n\n# Ba -> BaSO4\nx = np.linspace(-150, 0, 500)\ny = -x / 4 + delta_G3 / (R * T) / 2\n\nplt.plot(x, y, label='Ba -> BaSO4')\n\n# BaO -> BaSO4\nx = np.linspace(-150, 0, 500)\ny = - x / 3 + delta_G4 / (R * T) / 3 * 2\n\nplt.plot(x, y, label='BaO -> BaSO4')\n\n# BaS -> BaSO4\nx = np.linspace(-150, 0, 500)\nlog_PO2 = delta_G5 / (R * T) / 2\ny = np.full_like(x, log_PO2)\n\nplt.plot(x, y, label='BaS -> BaSO4')\n\n# BaS -> BaO + S2\nx = np.linspace(-150, 0, 500)\ny = x  + delta_G6 / (R * T) * 2\n\nplt.plot(x, y, label='BaS -> BaO + S2')\n\n# Draw\nplt.xlabel('log_PS2')\nplt.ylabel('log_PO2')\nplt.title('Graph of log_PS2 and log_PO2')\nplt.legend()\nplt.grid()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](生産プロセス_files/figure-html/cell-3-output-1.png){width=604 height=449}\n:::\n:::\n\n\n# 過去問まとめ\n\n<!-- \n::: {.callout-note collapse=\"true\"}\n### 理論\n\nThis is an example of a callout with a title.\n:::\n\n::: {.callout-tip collapse=\"true\"}\n### 解答\n\nThis is an example of a callout with a title.\n::: \n-->\n\n## 2014年度\n\n",
    "supporting": [
      "生産プロセス_files"
    ],
    "filters": [],
    "includes": {}
  }
}