project:
  type: website
  output-dir: docs

website:
  title: "My Journal"

  # Top bar of this website
  navbar:
    right: 
      - about.qmd
      - icon: book
        href: https://syosetu.org/novel/309340/
      - icon: github
        href: https://github.com/SerikaYuzuki
      - icon: twitter
        href: https://twitter.com/serika_yuzuki
      - icon: discord
        href: https://discord.gg/zUUkFzYZvK

  # Sidebar of this website
  sidebar:
    style: floating
    search: true

    # Contents of sidebar
    contents: 
      - about.qmd
      - section: UE5 Aura Courses
        contents: posts/ue5_aura_courses/*
      - section: AtCoder
        contents: posts/at_coder/*
      - section: Journal
        contents: posts/journal/*
      - section: 大学関連
        contents: posts/univ_lecs/*

    # Tools of sidebar
    tools: 
      - icon: book
        href: https://syosetu.org/novel/309340/
      - icon: github
        href: https://github.com/SerikaYuzuki
      - icon: twitter
        href: https://twitter.com/serika_yuzuki
      - icon: discord
        href: https://discord.gg/zUUkFzYZvK

  # Footer of this website
  page-footer:
    left: "My Journal"
    right: "Built with Quarto"

  # Back to top button in the bottom
  back-to-top-navigation: true

  # Page navigation at the right side
  page-navigation: true

format:
  html:

    # table-of-contents on the right
    toc: true

    # theme
    theme:
      # darkly is dark mode of flatly
      # if this is set, you can see switch button on the top right
      dark: darkly
      light: flatly

    # Commenting system via giscus
    comments:
      giscus: 
        repo: SerikaYuzuki/Developing-Journal
        theme: transparent_dark

    code-copy: true
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    highlight-style: vim-dark


