project:
  type: website

execute:
  freeze: auto
    
website:
  title: "芹香のブログ：セリポンポン 気軽にコメント残してね！"
  # Top bar of this website
  navbar:
    right: 
      - about.qmd
      - icon: book
        href: https://syosetu.org/novel/309340/
      - icon: github
        href: https://github.com/SerikaYuzuki
      - icon: twitter
        href: https://twitter.com/serika_yuzuki
      - icon: discord
        href: https://discord.gg/zUUkFzYZvK

  # Sidebar of this website
  sidebar:
    style: floating
    search: true

    # Contents of sidebar
    contents: 
      - about.qmd
      # - section: UE5 Aura Courses
      #   contents: posts/ue5_aura_courses/*
      # - section: UE5 Project
      #   contents: posts/ue5_project/*
      # - section: PlayGround
      #   contents: posts/play_ground/*
      # - section: AtCoder
      #   contents: posts/at_coder/*
      - section: 大学関連
        contents: posts/univ_lecs/
      - section: 収容所配布用
        contents: posts/収容所配布用/数学/
      - section: 技術関連
        contents: posts/tech/*

    # Tools of sidebar
    tools: 
      - icon: book
        href: https://syosetu.org/novel/309340/
      - icon: github
        href: https://github.com/SerikaYuzuki
      - icon: twitter
        href: https://twitter.com/serika_yuzuki
      - icon: discord
        href: https://discord.gg/zUUkFzYZvK

  # Footer of this website
  page-footer:
    left: "My Journal"
    right: "Built with Quarto"

  # Back to top button in the bottom
  back-to-top-navigation: true

  # Page navigation at the right side
  page-navigation: true    

format:

  html:
    include-in-header: 
      - text: |
          <script defer src="https://analytics.serika.work/script.js" data-website-id="2a8c65d4-a54f-413b-9f7f-09e7b71d0dea"></script>

    callout-appearance: simple

    # table-of-contents on the right
    toc: true
    toc-expand: 3
    toc-depth: 3

    # theme
    theme:
      # darkly is dark mode of flatly
      # if this is set, you can see switch button on the top right
      dark: darkly
      light: flatly

    # Commenting system via giscus
    comments:
      giscus: 
        repo: SerikaYuzuki/Developing-Journal
        theme: transparent_dark


    code-fold: true
    code-summary: "Show Code"
    code-copy: true
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    highlight-style: vim-dark


