{
  "hash": "540dd56a5cca740a688d7913af2c071a",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"材料電気化学\"\nauthor: \"Serika Yuzuki\"\ndate: \"2024-4-8\"\ncategories: [University, 2024]\nimage: \"images/thumbnail.png\"\nbibliography: ../../../bibliography.bib\n---\n\n$$\\require{mhchem}\n\\require{physics}\n$$\n\n# ノート\n## 電位関連の言葉の定義\n\n-   アノード反応: 電子を放出する反応\n-   カソード反応: 電子を受け取る反応\n\n## モル電気伝導率\n\nまず、コンダクタンスという言葉を定義する。これは、ある物質が電気を通す能力を表す物理量である。これは、電気伝導率抵抗の逆数である。\n\n$$\nG \\triangleq \\frac{1}{R} = \\frac{1}{\\rho}\\frac{A}{l} = \\kappa \\frac{A}{l}\n$$\n\n次にイオンのモル電気伝導率は次のように決まる。\n\n$$\n\\Lambda = \\frac{\\kappa}{c}\n$$\n\nここで、$\\kappa$ はイオンの電気伝導率、$c$ は**イオン**の濃度である。\n\n## コールラウシュの法則\n\n上のモル電気伝導率は強電解質にて次のような式が成り立つ。\n\n$$\n\\Lambda = \\Lambda^{\\infty} - k\\sqrt{c}\n$$\n\nここで、$\\Lambda^{\\infty}$ は無限希釈時のモル電気伝導率、$k$ はコールラウシュの定数である。\n\n次に、電解質には特有の守る電気電動率が存在しており、無限希釈時のモル電気伝導率は次のように表される。\n\n$$\n\\Lambda^{\\infty} = v_{+}\\lambda_{+}^{\\infty} + v_{-}\\lambda_{-}^{\\infty}\n$$ {#eq-molar_conductivity}\n\n## イオンの移動度\n\n$$\n\\lambda_{\\pm}^{\\infty} = z_{\\pm}F \\mu_{\\pm}^{\\infty}\n$$ {#eq-ion_mobility}\n\nここで、$z_{\\pm}$ はイオンの電荷、$F$ はファラデー定数、$\\mu_{\\pm}^{\\infty}$ は無限希釈時のイオンの移動速度である。\n\n## ストークスの法則\n\n$r_s$ を球体粒子の半径、$\\eta$ を流体の粘度、$\\rho_s$ を流体密度とする。\n\nまず仮定として、レイノルズ数が2以下の時\n\n$$\nRe = \\frac{2r_x\\rho_f u}{\\eta} <2\n$$\n\nこの時、球体粒子の持つ抵抗力は\n\n$$\n6\\pi \\eta r_s u\n$$\n\nになるという。この時、電場が働いている場合、終端速度は\n\n$$\nu = \\frac{E}{6\\pi \\eta r_s}\n$$\n\nとなる。ここでストークス半径はイオン半径とは違って、前者は移動度から計算され、後者は結晶半径から計算される。\n\n## 輸率\n\n輸率は次のように定義される。\n\n$$\nt_{\\pm}^{\\infty} = \\frac{v_{\\pm} \\lambda_{\\pm}^{\\infty}}{\\Lambda^{\\infty}}\n$$\n\n## 希釈律\n\nアレニウスの電離説では\n\n$$\n\\begin{align*}\nK_a &= \\frac{c_{\\ce{H^+}}c_{\\ce{A^-}}}{c_{\\ce{HA}}} \\\\\n&= \\frac{\\alpha^2}{1-\\alpha}c_{\\ce{HA}}\n\\end{align*}\n$$\n\nなどとなっていたが、\n\n$$\n\\Lambda = \\alpha \\lambda_{-} + \\alpha \\lambda_{+} = \\alpha \\Lambda^{\\infty}\n$$ {#eq-dilution_law_alpha}\n\nと考えることによって、\n\n$$\nK_a = \\frac{\\Lambda^2}{\\Lambda^{\\infty}(\\Lambda^{\\infty} - \\Lambda)}c\n$$ {#eq-dilution_law}\n\nとすることができて、これが希釈溶液ではそれなりに実験値と変わらないようだ。\n\n## イオン活量\n\n$$\n\\begin{aligned}\nG &= f(T,P,n_1,n_2,\\cdots) \\\\\n\\dd G &= \\dv{G}{T} \\dd T + \\dv{G}{P} \\dd P + \\sum_i \\dv{G}{n_i} \\dd n_i \\\\\n\\end{aligned}\n$$\n\n電気化学では多くの場合、温度と圧力が一定なので、\n\n$$\n\\dd G = \\sum_i \\left( \\pdv{G}{n_i} \\right) \\dd n_i = \\sum_i \\mu_i \\dd n_i\n$$\n\nこの時、$\\mu_i$ をイオンの標準化学ポテンシャルという。これは、理想溶液では次のような式に従う。\n\n$$\n\\mu_i = \\mu_i^0 + RT \\ln x_i\n$$\n\nここで、 $x_i$ はモル分率である。ただしこれは理想溶液のみで、実際の溶液では次のような式に従う。\n\n$$\n\\mu_i = \\mu_i^0 + RT \\ln a_i\n$$\n\nここで、$a_i$ はイオンの活量である。これは、次のように定義される。\n\n$$\na_i = \\gamma_i x_i\n$$\n\nここで、$\\gamma_i$ は活量係数である。この値は測定困難である。\n\n## 平均活量係数\n\n1-1型のイオンの平均活量は次のように定義される。\n\n$$\n\\mu = \\mu_+ + \\mu_- = \\mu_+^0 + \\mu_-^0 + RT \\ln (a_+a_-)\n$$\n\nここで、電解質の活量は\n\n$$\na = a_+ a_-\n$$\n\nイオンの平均活量は $\\sqrt{a}$ となり、平均活量係数は $\\gamma = \\sqrt{\\gamma_+\\gamma_-}=\\sqrt{a_+a_-/c^2}$ となる。\n\n$\\nu_+, \\nu_-$ 型のイオンの平均活量係数は次のようになる。\n\n$$\n\\begin{aligned}\n\\mu &= \\nu_+ \\mu_+^0 + \\nu_- \\mu_-^0 + RT \\ln (a_+^{\\nu_+}a_-^{\\nu_-})\\\\\na &= a_+^{\\nu_+}a_-^{\\nu_-}\\\\\na_{\\pm} &= (a_+^{\\nu_+}a_-^{\\nu_-})^{1/(\\nu_+ + \\nu_-)}\\\\\n\\gamma_{\\pm} &= (a_+^{\\nu_+}a_-^{\\nu_-})^{1/(\\nu_+ + \\nu_-)}/c\\\\\n&= a_{\\pm}/c\n\\end{aligned}\n$$\n\nここで注意すべきなのは、平均は $\\nu_-+\\nu_+$ で平均化すること。\n\n## デバイ・ヒュッケルの法則\n\n要するに、ボルツマン分布でイオンを考えて、それとポアソンの法則を組み合わせると、イオンの平均活量係数が求まる。\n\nボルツマン分布でイオン内のイオン分布次のようになる。\n\n$$\nn_i^{'} = n_i \\exp \\left( -\\frac{z_ie\\phi(r)}{kT} \\right)\n$$\n\nここで、$n_i^{'}$ はイオンの濃度、$n_i$ は無限遠における密度、$z_i$ はイオンの電荷、$e$ は電子の電荷、$\\phi(r)$ は電位、$k$ はボルツマン定数、$T$ は温度である。\n\n各種イオンに対してこれが成り立つので、電荷密度は次のようになる。\n\n$$\n\\rho(r) = \\sum_i z_i e n_i \\exp \\left( -\\frac{z_ie\\phi(r)}{kT} \\right)\n$$\n\nこれを一次近似すると、0次の項が消えて、1次の項だけが残る。\n\n$$\n\\rho(r) = -\\frac{e^2\\phi (r)}{kT} \\left( \\sum_i n_i z_i^2 \\right) = -\\frac{2 e^2}{kT} \\left( \\sum_i \\frac{1}{2} n_i z_i^2 \\phi (r) \\right)\n$$\n\nここで、ガウスの法則のポテンシャルの方の式を考えて、\n\n$$\n\\nabla^2 \\phi = -\\frac{\\rho}{\\varepsilon} = -\\frac{\\rho}{\\epsilon_0 \\epsilon_r}\n$$\n\nこれらを合わせて、\n\n$$\n\\nabla^2 \\phi = \\frac{1}{\\epsilon_0 \\epsilon_r} \\frac{2e^2}{kT} \\left( \\sum_i \\frac{1}{2} n_i z_i^2 \\right) \\phi\n$$\n\nこれはヘルムホルツ方程式 $\\nabla^2 \\phi = \\frac{\\phi}{\\lambda_D^2}$ と呼ばれる偏微分方程式で、解が\n\n$$\n\\phi = \\dfrac{A}{r} \\exp\\left(-\\frac{r}{\\lambda_D}\\right) + \\dfrac{B}{r} \\exp\\left(\\frac{r}{\\lambda_D}\\right)\n$$\n\nになるんだが、この時の $\\lambda_D$ がデバイ・ヒュッケル長さである。\n\n$$\n\\lambda_D = \\qty(\\dfrac{2e^2}{\\epsilon_0 \\epsilon_r kT} \\sum_i \\frac{1}{2} c_i z_i^2)^{-1/2} \n$$\n\n実際に解いていくと次のようになる。\n\n$$\n\\phi(r) = \\frac{ze}{4 \\pi \\epsilon_0 \\epsilon_r} \\exp\\left(-\\frac{r}{\\lambda_D}\\right)\n$$\n\n$$\n\\rho (r) = -\\frac{ze}{4\\pi \\lambda_D^2 r}\\exp\\left(-\\frac{r}{\\lambda_D}\\right)\n$$\n\nとなる。ここでさらに電位を展開すると、\n\n$$\n\\phi(r) = \\frac{ze}{4\\pi \\epsilon_0 \\epsilon_r r} - \\frac{ze}{4\\pi \\epsilon_0 \\epsilon_r \\lambda_D}\n$$\n\nこの第一項は中心電荷による電位で、第二項はイオン相互作用による電位である。\n\n次に充電することを考える。中心電化による電位は考えなくてもいいので、\n\n$$\nW = N_A \\int_0^{ze} - \\frac{ze}{4\\pi \\epsilon_0 \\epsilon_r \\lambda_D} \\dd ze = -N_A \\frac{(ze)^2}{8\\pi \\epsilon_0 \\epsilon_r \\lambda_D}\n$$\n\n理想溶液と実在溶液の化学ポテンシャルの差は\n\n$$\n\\Delta \\mu = \\mu_i^0 +RT \\ln a_i - (\\mu_i^0 + RT \\ln x_i) = RT \\ln \\gamma_i\n$$\n\nこれらがつながるので、ごちゃごちゃした計算を略すと\n\n$$\n\\ln \\gamma_i = -z^2\\frac{1}{8\\pi}\\left(\\frac{2N_A}{1000}\\right)^{1/2}\\left(\\frac{e^2}{\\epsilon_0\\epsilon_r kT}\\right)^{3/2}\\left(\\sum_i \\frac{1}{2}c_iz_i^2\\right)^{1/2}\n$$\n\nこれを次のように記述する。\n\n$$\n\\ln \\gamma_i = -A^{\\ast}z^2 I^{1/2}\n$$ {#eq-debye_huckel}\n\n$$\nI \\triangleq \\sum_i \\frac{1}{2}c_iz_i^2\n$$ {#eq-ion_strength}\n\nで、イオン強度と呼ばれる。この式を代入することによって、平均活量計数が求められる。\n\n$$\n\\begin{aligned}\n\\ln \\gamma_{\\pm} & = \\frac{1}{\\nu_++\\nu_-}\\left( \\nu_+ \\ln \\gamma_+ + \\nu_- \\ln \\gamma_- \\right)\\\\\n& = \\frac{-A^{\\ast}}{\\nu_++\\nu_-} \\left( \\nu_+ z_+^2 I^{1/2} + \\nu_- z_-^2 I^{1/2} \\right)\\\\\n&= A^{\\ast} z_+ z_- I^{1/2}\n\\end{aligned}\n$$\n\nこれをデバイ・ヒュッケルの極限法則という。ただし、これはイオン直径が高い時と、濃度が高い場合に問題になってくるので、その補正を入れると、\n\n$$\n\\ln \\gamma_{\\pm} = \\frac{A^{\\ast}z_+z_-I^{1/2}}{1+BaI^{1/2}} + bI\n$$\n\nとなる。ここで、$B$ はイオンの直径に関するパラメータで、 $a$ はイオンの半径である。\n\nここまでで大事な式は次のようになる。\n\n**イオン強度**\n\n$$\nI = \\frac{1}{2} \\sum_i c_iz_i^2\n$$\n\n**デバイ・ヒュッケルの極限法則**\n\n$$\n\\ln \\gamma_{\\pm} = A^{\\ast} z_+ z_- I^{1/2}\n$$\n\nただし、\n\n$$\nA^{\\ast} = \\frac{1}{8\\pi}\\qty(\\frac{2N_A}{1000})^{1/2}\\left(\\frac{e^2}{\\epsilon_0\\epsilon_r kT}\\right)^{3/2}\n$$\n\nこの値の $25^{\\circ}\\symup{C}$ における値は $0.509$ である。\n\nこれまでは希釈溶液の話だったが、濃度が高い時含めて拡張した式として\n\n$$\n\\ln \\gamma_{\\pm} = \\frac{A^{\\ast}z_+ z_- I^{1/2}}{1+BaI^{1/2}} + bI\n$$\n\n## ボルンの式 {#sec-born_eq}\n\n真空と溶液内には自由エネルギー差があるのだが、その差ってのはイオンを真空から溶液内に移すだけの仕事の差だと考えるモデル。\n\n$$\nw = \\int_0^{Ze} \\frac{q}{4\\pi r \\epsilon_0 \\epsilon_r} \\dd q = \\frac{Ze^2}{8\\pi \\epsilon_0 \\epsilon_r}\n$$\n\nこれを真空から溶液内に移すと、\n\n$$\n\\Delta G_S^\\circ = \\frac{ZN_Ae^2}{8\\pi \\epsilon_0 r} \\qty(1 - \\frac{1}{\\epsilon_r})\n$$\n\nこれをボルン式と呼んでいる。\n\n\n## ネルンストの式 {#sec-nerst_eq}\n\nイオンの電気化学ポテンシャルは次の式で表される。\n\n$$\n\\mu_i = \\mu_i^0 + RT \\ln a_i + z_i F \\phi\n$$\n\nここで、$\\mu_i^0$ は標準電気化学ポテンシャル、$a_i$ は活量、$z_i$ はイオンの電荷、$F$ はファラデー定数、$\\phi$ は電位である。\n\nここで酸化体、還元体の電気化学ポテンシャルを考えると、\n\n$$\n\\ce{Ox^{z+}} + ne^- \\ce{<=> Red^{(z-n)+}}\n$$\n\n$$\n\\begin{aligned}\n\\mu_{\\ce{Ox}} &= \\mu_{\\ce{Ox}}^{O} + RT \\ln a_{\\ce{Ox}} + z_i F \\phi_{Liq} \\\\\n\\mu_{\\ce{Red}} &= \\mu_{\\ce{Red}}^{O} + RT \\ln a_{\\ce{Red}} + (z-n)F \\phi_{Liq} \\\\\n\\mu_{e^-} &= \\mu_{e^-}^{O} + RT \\ln a_{e^-} - F \\phi_{M}\n\\end{aligned}\n$$\n\nとなる。ここで注意すべきは、$\\phi_{Liq}$ と $\\phi_{M}$ はそれぞれ溶液と電極の電位である。このような状態が平衡に達しているとき、\n\n$$\n\\mu_{\\ce{Ox}} + n\\mu_{e^-} = \\mu_{\\ce{Red}} \n$$\n\nとなる。これを整理すると、\n\n$$\n\\Delta \\phi = \\phi_{M} - \\phi_{Liq} = \\frac{\\mu_{\\ce{Ox}} + n\\mu_{e^-} - \\mu_{\\ce{Red}}}{nF} + \\frac{RT}{nF} \\ln \\frac{a_{\\ce{Ox}}}{a_{\\ce{Red}}}\n$$\n\nとなる。ここで、 $\\Delta G^O = -(\\mu_{\\ce{Ox}} + n\\mu_{e^-} - \\mu_{\\ce{Red}})$ で、 $E^O = - \\Delta G^O/nF$ と標準電位を定義して整理すると、\n\n$$\n\\Delta \\phi = E^O + \\frac{RT}{nF} \\ln \\frac{a_{\\ce{Ox}}}{a_{\\ce{Red}}}\n$$ {#eq-nerst_eq}\n\nとなる。これをネルンストの式という。ただし、ネルンストの式と呼ばれているものは数種類以上存在しているらしく、そこらの混乱について端的にわかりやすい解説は @電気化学ーそこを知りたい議論したい にある。\n\n<!-- \n::: {.callout-note collapse=\"true\"}\n##### 理論\n\nThis is an example of a callout with a title.\n:::\n\n::: {.callout-tip collapse=\"true\"}\n##### 解答\n\nThis is an example of a callout with a title.\n::: \n-->\n\n# 演習問題\n\n## 問題1\n\n### 1-1. \n\nCuめっき反応を、電流密度50 mA/cm²にて10分間行った。100%の電流効率を仮定した際、めっき膜の厚さを求めよ。\n\n反応式：  \n$$\n\\mathrm{Cu^{2+} + 2e^- \\rightarrow Cu}\n$$\n\n与えられたデータ：\n- 電流密度：50 mA/cm²\n- めっき時間：10 分 = 600 秒\n- 電流効率：100%\n- Cuの原子量：63.55\n- Cuの密度：8.94 g/cm³\n- ファラデー定数：$F = 96500 \\ \\mathrm{C/mol}$\n\n::: {.callout-tip collapse=\"true\"}\n#### 解答\n\n50 $\\symup{mA/cm}^2$ で10分間電流を流すと、合計で 30 $\\symup{C/cm}^2$ の電荷が流れる。これは、1 $\\symup{cm}^2$ の面積につき 30 $\\symup{C}$ の電荷が流れたことを意味する。\n\n1 $\\symup{mol}$ の電子は $eN_A = 96485 \\symup{C/mol}$ の電荷を持つので、1 $\\symup{cm}^2$ の面積につき 30 $\\symup{C}$ の電荷が流れることは、$30/96485 = 3.1 \\times 10^{-4} \\symup{mol}$ の電子が流れたことを意味する。つまり、$1.6 \\times 10^{-4} \\symup{mol}$ の $\\ce{Cu}$ が生成したことになるわけで、これの重量は、$1.6 \\times 10^{-4} \\times 63.5 = 1.0 \\times 10^{-2} \\symup{g}$ である。\n\n膜の密度が $8.94 \\symup{g/cm^3}$ であることを考慮すると、面積あたりの生成量である $1.0 \\times 10^{-2} \\symup{g/cm^2}$ で割ってやれば、 $1.1 \\times 10^{-3} \\symup{cm} = 1.1 \\symup{\\mu m}$ となる。\n\n:::\n\n\n### 1-2. \n\n温度 1 eV は 何 [K] に対応するか求めよ。\n\n（※ 厳密には正しくない換算かもしれないが、eVの感覚を得るために行う。）\n\n与えられた定数：\n- $1\\ \\mathrm{eV} = 1.602 \\times 10^{-19}\\ \\mathrm{J}$\n- ボルツマン定数：$k_B = 1.381 \\times 10^{-23}\\ \\mathrm{J/K}$\n\n::: {.callout-tip collapse=\"true\"}\n#### 解答\n\n$1 \\symup{eV}$ とは、$1.6 \\times 10^{-19} \\symup{J}$ である。このエネルギーを内部運動エネルギーに持つ何らかの粒子群の温度は、３次元運動として考えれば、$\\frac{3}{2}k_BT = 1.6 \\times 10^{-19} \\symup{J}$ となる。ここで、$k_B = 1.38 \\times 10^{-23} \\symup{J/K}$ である。これを解くと、$T = 7.7 \\times 10^3 \\symup{K}$ となる。\n\nただし厳密的には、 $1 \\symup{eV} = k_BT$ から、 $T= 1.16 \\times 10^4 \\symup{K}$ となる。これについては理解できるまでに時間がかかりそうだ。\n\n:::\n\n\n### 1-3.\n金属を100%の電流効率でアノード溶解したとき、単位時間当たり単位面積当たりの溶解量は、電流密度に比例する。  \nFe, Zn, Alの3種の金属について、1 [A/m²] の電流密度に対応する溶解量 [g·m⁻²·h⁻¹] を求めよ。  \nなお、Fe, Znは2価、Alは3価で溶解するとし、それぞれの原子量は、Fe: 55.85, Zn: 65.38, Al: 26.98 とする。\n\n::: {.callout-tip collapse=\"true\"}\n#### 解答\n\nこれについては 2.1 と同じ計算を行うことになる。\n\n$1 \\symup{A \\cdot m^{-2}}$ によって流れる電気量は $1/96485 = 1.036 \\times 10^{-5} \\symup{mol \\cdot m^{-2} \\cdot s^{-1}}$ である。これに $\\ce{Fe, Zn, Al}$ のそれぞれの価数で割って、原子量で掛けることで、それぞれの生成質量の速度を求めることができる。\n\n::: {#35828f5b .cell execution_count=1}\n``` {.python .cell-code}\nimport numpy as np\n\n# 定数\nF = 96485  # C/mol\nmolar_charge = 1 / F  # mol/C\n\n# 各金属の価数と原子量\nmetals = {\n    'Fe': {'valence': 2, 'molar_mass': 55.85},\n    'Zn': {'valence': 2, 'molar_mass': 65.38},\n    'Al': {'valence': 3, 'molar_mass': 26.98}\n}\n\n# 電流密度\ncurrent_density = 1  # A/m^2\n\n# 各金属の生成質量の速度を計算\nfor metal, properties in metals.items():\n    valence = properties['valence']\n    molar_mass = properties['molar_mass']\n    \n    # 電気量\n    charge_per_m2 = current_density * molar_charge  # mol/m^2/s\n    \n    # 生成質量の速度\n    mass_production_rate = charge_per_m2 * molar_mass / valence  # g/m^2/s\n    print(f\"{metal}: {mass_production_rate:.3e} g/m^2/s\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nFe: 2.894e-04 g/m^2/s\nZn: 3.388e-04 g/m^2/s\nAl: 9.321e-05 g/m^2/s\n```\n:::\n:::\n\n\n:::\n\n### 1-4.\nアルカリ水溶液の電気分解によって水10 gを1時間で分解したい。何 A の定電流を流したらよいか求めよ。\n\n::: {.callout-tip collapse=\"true\"}\n#### 解答\n\n水 $10 \\symup{g}$ を電気分解するには、$10/18 \\times 2 = 1.12 \\symup{mol}$ の電子が必要で、\\$ 1 \\symup{A} \\$ で $1/96485 = 1.036 \\times 10^{-5} \\symup{mol/s}$ の電子が流れるので、 $3600 \\symup{s}$ で完全に電気分解するには、 $1.12/(1.036 \\times 10^{-5} \\times 3600) = 30 \\symup{A}$ が必要である。\n\n:::\n\n### 1-5.\n二酸化チタン（アナターゼ型）のバンドギャップは約 3.2 eV、シリコンのものは約 1.1 eV と報告されている。  \nバンドギャップに対応した、光の波長 [nm] を計算せよ。  \nλ [nm] = 1240 / hν [eV] の関係より（各自確認のこと） \n\n::: {.callout-tip collapse=\"true\"}\n#### 解答\n\n$E= hc/\\lambda$ なので、 $\\lambda = hc/E$ となる。これを $\\symup{eV}$ に変換すると、 $\\lambda = 1240/E$ となる。これを用いて、 $\\lambda = 1240/1.1 = 1127 \\symup{nm}$ となる。次に、 $\\lambda = 1240/3.2 = 387 \\symup{nm}$ となる。\n\n:::\n\n## 問題2\n\n| 陽イオン           | $\\lambda^\\infty (\\times 10^{-4} \\symup{S \\cdot m^2 \\cdot mol^{-1}})$ | 陰イオン              | $\\lambda^\\infty (\\times 10^{-4} \\symup{S \\cdot m^2 \\cdot mol^{-1}})$ |\n|------------------|---------------------|-----------------------|----------------------|\n| $\\ce{H^+}$               | 349.82              | $\\ce{OH^-}$                  | 198.6                |\n| $\\ce{Li^+}$              | 38.69               | $\\ce{F^-}$                   | 54.4                 |\n| $\\ce{Na^+}$              | 50.11               | $\\ce{Cl^-}$                  | 76.35                |\n| $\\ce{K^+}$               | 73.5                | $\\ce{Br^-}$                  | 78.1                 |\n| $\\ce{Rb^+}$              | 77.8                | $\\ce{I^-}$                   | 76.8                 |\n| $\\ce{Cs^+}$              | 77.3                | $\\ce{NO3^-}$                 | 71.4                 |\n| $\\ce{Ag^+}$              | 61.9                | $\\ce{HCO3^-}$                | 44.5                 |\n| $\\ce{1/2 Be^{2+}}$         | 45                  | $\\ce{HCOO^-}$                | 54.6                 |\n| $\\ce{1/2 Fe^{2+}}$         | 54                  | $\\ce{1/3 [Fe(CN)6]^{3-}}$      | 101                  |\n| $\\ce{1/2 Cu^{2+}}$         | 55                  | $\\ce{1/4 [Fe(CN)6]^{4-}}$      | 111                  |\n| $\\ce{1/2 Zn^{2+}}$         | 52.8                |                       |                      |\n| $\\ce{1/2 Cd^{2+}}$         | 54                  |                       |                      |\n| $\\ce{1/2 Hg^{2+}}$         | 53                  |                       |                      |\n| $\\ce{1/2 Pb^{2+}}$         | 71                  |                       |                      |\n| $\\ce{1/3 Al^{3+}}$         | 61                  |                       |                      |\n| $\\ce{1/3 Cr^{3+}}$         | 67                  |                       |                      |\n| $\\ce{1/3 Fe^{3+}}$         | 68                  |                       |                      |\n| $\\ce{1/3 La^{3+}}$         | 69.6                |                       |                      |\n| $\\ce{1/3 Ce^{3+}}$         | 70                  |                       |                      |\n| $\\ce{NH4^+}$             | 73.5                |                       |                      |\n| $\\ce{(CH3)4N^+}$         | 45.3                |                       |                      |\n| $\\ce{(C2H5)4N^+}$         | 33.0                |                       |                      |\n| $\\ce{(n-C3H7)4N^+}$       | 23.5                |                       |                      |\n| $\\ce{(n-C4H9)4N^+}$       | 19.1                |                       |                      |\n:無限希釈におけるイオンのモル電気伝導率\n\n> ※ 多価イオンについては $\\lambda^\\infty / |z|$ の値を示してある。\n\n---\n\n### 2-1. \n\n表「無限希釈におけるイオンのモル電気伝導率」を用いて、$\\ce{K^+, Ca^{2+}, Cl^-, SO4^{2-}}$ の移動度を求めよ。  \n$$\\lambda^\\infty = z_i F u_i \\Rightarrow u_i = \\lambda^\\infty / |z_i| F$$  \n（表の値はすでに $\\lambda/z$ の単位 [$\\symup{\\Omega^{-1} m^2 mol^{-1}}$] で与えられている）\n\n::: {.callout-tip collapse=\"true\"}\n#### 解答\n\nイオン移動度の式は (@eq-ion_mobility) だから、\n\n::: {#5154ef05 .cell execution_count=2}\n``` {.python .cell-code}\n# 定数\nF = 96485  # C/mol\n\n# 各物質のイオンモル伝導率\nmetals = {\n    'K+': {'z': 1, 'lambda': 73.5},\n    'Ca2+': {'z': 2, 'lambda': 119},\n    'Cl-': {'z': 1, 'lambda': 76.35},\n    'SO42-': {'z': 2, 'lambda': 160},\n}\n\n# 各物質のイオン移動度を計算\nfor metal, properties in metals.items():\n    z = properties['z']\n    lambda_ = properties['lambda']\n    \n    # イオンモル伝導率\n    ion_mobility = lambda_ / z / F  # m^2/V/s\n    print(f\"{metal}: {ion_mobility:.3e} m^2/V/s\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nK+: 7.618e-04 m^2/V/s\nCa2+: 6.167e-04 m^2/V/s\nCl-: 7.913e-04 m^2/V/s\nSO42-: 8.291e-04 m^2/V/s\n```\n:::\n:::\n\n\n:::\n\n### 2-2.\n$\\ce{Li^+}$ は $\\ce{Cs^+}$ と比べ、「$r_c$ は小さいが、$r_s$ は大きい」  \nその理由を考察せよ。ただし、 $r_c$ はイオン半径、 $r_s$ はストークス半径である。\n\n::: {.callout-tip collapse=\"true\"}\n#### 解答\n\nストークス半径は流体中の水和イオンの見かけ上の大きさで、イオン半径は結晶中のイオンの大きさである。\n\n$\\ce{Li+}$ は $\\ce{Cs+}$ に比べて電荷密度が高く、水和が強いために $r_s$ が大きくなる。逆に、 $\\ce{Cs+}$ は電荷密度が低く、水和が弱いために $r_s$ が小さくなる。\n\n:::\n\n### 2-3.\n酢酸の無限希釈モル伝導率を「無限希釈のイオンのモル電気伝導率」から求めよ。  \n与えられた値：  \n- $\\ce{H^+}$：349.82  \n- $\\ce{CH3COO^-}$：40.9  \n- 合計：390.72 [$\\symup{S \\cdot cm^2 \\cdot mol^{-1}}$]\n\n::: {.callout-tip collapse=\"true\"}\n#### 解答\n\nこの式 (@eq-molar_conductivity) を用いて、 $\\ce{CH3COOH}$ のモル電気伝導率を求める。\n\n$$\\Lambda^{\\infty}[\\ce{CH3COOH}] = 349.82 + 40.9 = 390.7 \\ \\text{S}\\text{m}^2\\text{mol}^{-1}$$\n\n:::\n\n### 2-4.\n0.02 M（=0.02 mol/l）酢酸水溶液の導電率が $2.31 \\times 10^{-4} \\symup{S \\cdot cm^{-1}}$ であった。  \n上記無限希釈モル伝導率を用い、酢酸の電離度と解離定数を求めよ。\n\n::: {.callout-tip collapse=\"true\"}\n#### 解答\n\n式 (@eq-dilution_law) を用いる。\n\n::: {#41d57182 .cell execution_count=3}\n``` {.python .cell-code}\n# 定数\nc = 0.02  # mol/L\nlambda_infinity = 390.7e-4  # S m^2 mol^-1\nlambda_ = 2.31e-5 / c  # S m^2 mol^-1\n\n# 酢酸の電離度と電離定数を計算\nalpha = lambda_ / lambda_infinity\nKa = (lambda_**2) / (lambda_infinity * (lambda_infinity - lambda_)) * c\nprint(f\"電離度: {alpha:.3f}\")\nprint(f\"電離定数: {Ka:.3e} mol/L\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n電離度: 0.030\n電離定数: 1.801e-05 mol/L\n```\n:::\n:::\n\n\n:::\n\n### 2-5.\n半径 1 cm の導体球に $10^{-13} \\symup{mol}$ の電子を乗せ、真空中におくと、表面電位はいくらになるか求めよ。  \n（真空の誘電率 $\\epsilon_0 = 8.854 \\times 10^{-12} \\symup{C^2/N \\cdot m^2}$）\n\n::: {.callout-tip collapse=\"true\"}\n#### 解答\n\n$$\\phi = \\frac{1}{4\\pi\\epsilon_0} \\frac{Q}{r} = \\frac{1}{4\\pi\\epsilon_0} \\frac{10^{-13} \\times F}{1 \\times 10^{-2}} = 8.7 \\times 10^{3} \\symup{V}$$\n\n::: {#e096c2b4 .cell execution_count=4}\n``` {.python .cell-code}\nimport numpy as np\n# 定数\nepsilon_0 = 8.854e-12  # C^2/Jm\nQ = 10**-13 * 96485  # C\nr = 1e-2  # m\nphi = 1 / (4 * np.pi * epsilon_0) * Q / r\nprint(f\"表面電位: {phi:.3e} V\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n表面電位: 8.672e+03 V\n```\n:::\n:::\n\n\n:::\n\n\n### 2-6.\n酢酸を水酸化ナトリウム溶液で伝導度滴定した場合の滴定曲線は右図のようになる。  \n各イオンの電気伝導率に対する寄与を、前述のラム分図のように示せ。\n\n::: {.callout-tip collapse=\"true\"}\n#### 解答\n\n滴定前と、当量点以降では $\\ce{H+, OH^-}$ の寄与が大きくなる。それ以外の線形的増加部分は、 $\\ce{Na+}$ の寄与が大きくなる。\n\n:::\n\n## 問題3\n\n### 3-1.\n\n$\\ce{NaCl}$ を 0.1 M、$\\ce{Al2(SO4)3}$ を 0.01 M 含む水溶液（どちらも $\\alpha = 1$ とする）の**イオン強度**は何 M になるか。 また、そのうち $\\ce{NaCl}$ の**分担割合**は何 % かもとめよ。\n\n::: {.callout-note collapse=\"true\"}\n#### 理論\n\nイオン強度の定義式は (@eq-ion_strength) である。\n\nここで、$c_i$ はイオンの濃度、$z_i$ はイオンの電荷数というのを注意！　イオン濃度じゃなくて、水溶液濃度で計算してハマったのでまじで注意。\n:::\n\n::: {.callout-tip collapse=\"true\"}\n#### 解答\n\n$$\n\\begin{aligned}\nI_{\\ce{NaCl}} &= \\frac{1}{2} \\left( c_{\\ce{Na+}} z_{\\ce{Na+}}^2 + c_{\\ce{Cl-}} z_{\\ce{Cl-}}^2 \\right) \\\\\n&= \\frac{1}{2} \\left( 0.1 \\times 1^2 + 0.1 \\times (-1)^2 \\right) \\\\\n&= 0.1 \\ \\text{M} \\\\\nI_{\\ce{Al2(SO4)3}} &= \\frac{1}{2} \\left( c_{\\ce{Al3+}} z_{\\ce{Al3+}}^2 + c_{\\ce{SO42-}} z_{\\ce{SO42-}}^2 \\right) \\\\\n&= \\frac{1}{2} \\left( 0.01 \\times 3^2 + 0.03 \\times (-2)^2 \\right) \\\\\n&= 0.15 \\ \\text{M} \\\\\nI_{\\ce{NaCl}} + I_{\\ce{Al2(SO4)3}} &= 0.1 + 0.15 = \\boxed{0.25 \\ \\text{M} } \\\\\n\\frac{I_{\\ce{NaCl}}}{I_{\\ce{NaCl}} + I_{\\ce{Al2(SO4)3}}} &= \\frac{0.1}{0.25} \\times 100 = \\boxed{40 \\ \\%}\n\\end{aligned}\n$$\n\n::: {#2b9d4d35 .cell execution_count=5}\n``` {.python .cell-code}\n# 定数\nc_Na = 0.1  # mol/L\nc_Cl = 0.1  # mol/L\nc_Al2 = 0.02  # mol/L\nc_SO4 = 0.03  # mol/L\nz_Na = 1\nz_Cl = -1\nz_Al = 3\nz_SO4 = -2\n# イオン強度の計算\nI = 0.5 * (c_Na * z_Na**2 + c_Cl * z_Cl**2 + c_Al2 * z_Al**2 + c_SO4 * z_SO4**2)\nprint(f\"イオン強度: {I:.3f} M\")\n# 分担割合の計算\nfraction_NaCl = (c_Na * z_Na**2 + c_Cl * z_Cl**2) / (c_Na * z_Na**2 + c_Cl * z_Cl**2 + c_Al2 * z_Al**2 + c_SO4 * z_SO4**2)\nprint(f\"分担割合: {fraction_NaCl:.3%}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nイオン強度: 0.250 M\n分担割合: 40.000%\n```\n:::\n:::\n\n\n:::\n\n### 3-2.\n\n$\\ce{CaCl2}$ 水溶液（強電解質溶液：$25^{\\circ}\\symup{C}$）の、0.001 M および 0.01 M における **イオン強度**と**デバイ半径**を計算せよ。\n\n::: {.callout-note collapse=\"true\"}\n#### 理論\n\nデバイ半径は次のように定義される。\n\n$$\n\\begin{aligned}\n\\lambda_D &= \\qty(\\dfrac{2e^2}{\\epsilon_0 \\epsilon_r kT} \\sum_i \\frac{1}{2} c_i z_i^2)^{-1/2} \\\\\n&= \\qty(\\dfrac{2e^2}{\\epsilon_0 \\epsilon_r kT} I_n)^{-1/2}\n\\end{aligned}\n$$\n\nここで、 $n_i$ はイオン濃度。ただし単位は $\\symup{mol\\ m^{-3}}$ ではなく、 $\\symup{m^{-3}}$ であることに注意。つまり、 $N_A$ を掛けてやる必要がある。\n\n一応の一応、デバイ長を導くことになったら次のように考えよう。\n\nボルツマン分布\n\n$$\nn_i^{'} = n_i \\exp \\left( -\\frac{z_ie\\phi(r)}{kT} \\right)\n$$\n\nこれから濃度分布\n\n$$\n\\begin{aligned}\n\\rho(r) &= \\sum_i z_i e n_i \\exp \\left( -\\frac{z_ie\\phi(r)}{kT} \\right) \\\\\n&\\approx -\\frac{e^2\\phi (r)}{kT} \\left( \\sum_i n_i z_i^2 \\right) \\\\\n&= -\\frac{2 e^2}{kT} \\left( \\sum_i \\frac{1}{2} n_i z_i^2 \\phi (r) \\right)\n\\end{aligned}\n$$\n\nこれでポアソン方程式\n\n$$\n\\nabla^2 \\phi = \\frac{\\phi}{\\lambda_D^2}\n$$\n\nを解いて $\\lambda_D$ を求める。\n\n:::\n\n::: {.callout-tip collapse=\"true\"}\n#### 解答\n\nイオン強度は、\n\n$$\n\\begin{aligned}\nI_{\\ce{CaCl2}, \\mathrm{0.001 \\ M}} &= \\frac{1}{2} \\left( c_{\\ce{Ca2+}} z_{\\ce{Ca2+}}^2 + c_{\\ce{Cl-}} z_{\\ce{Cl-}}^2 \\right) \\\\\n&= \\frac{1}{2} \\left( 0.001 \\times 2^2 + 0.002 \\times (-1)^2 \\right) \\\\\n&= 0.003 \\ \\text{M} \\\\\nI_{\\ce{CaCl2}, \\mathrm{0.01 \\ M}} &= \\frac{1}{2} \\left( c_{\\ce{Ca2+}} z_{\\ce{Ca2+}}^2 + c_{\\ce{Cl-}} z_{\\ce{Cl-}}^2 \\right) \\\\\n&= \\frac{1}{2} \\left( 0.01 \\times 2^2 + 0.02 \\times (-1)^2 \\right) \\\\\n&= 0.03 \\ \\text{M} \\\\\n\\end{aligned}\n$$\n\nデバイ半径は\n\n$$\n\\begin{aligned}\n\\lambda_D &= \\qty(\\dfrac{2e^2}{\\epsilon_0 \\epsilon_r kT} \\sum_i \\frac{1}{2} c_i z_i^2)^{-1/2} \\\\\n&= \\qty(\\dfrac{2e^2}{\\epsilon_0 \\epsilon_r kT} I_n)^{-1/2} \\\\\n\\lambda_{D,\\mathrm{0.001 \\ M}} &= \\qty(\\dfrac{2e^2}{\\epsilon_0 \\epsilon_r kT} I_{\\ce{CaCl2}, \\mathrm{0.001 \\ M}})^{-1/2} \\\\\n&= \\qty(\\dfrac{2e^2}{\\epsilon_0 \\epsilon_r kT} 0.003)^{-1/2} \\\\\n&= 5.55 \\times 10^{-9} \\ \\text{m} \\\\\n\\lambda_{D,\\mathrm{0.01 \\ M}} &= \\qty(\\dfrac{2e^2}{\\epsilon_0 \\epsilon_r kT} I_{\\ce{CaCl2}, \\mathrm{0.01 \\ M}})^{-1/2} \\\\\n&= \\qty(\\dfrac{2e^2}{\\epsilon_0 \\epsilon_r kT} 0.03)^{-1/2} \\\\\n&= 1.76 \\times 10^{-9} \\ \\text{m} \\\\\n\\end{aligned}\n$$\n\n::: {#b82c37c5 .cell execution_count=6}\n``` {.python .cell-code}\nimport numpy as np\n# 定数\nepsilon_0 = 8.854e-12  # C^2/Jm\nepsilon_r = 78.5  # 水の誘電率\nk = 1.38e-23  # J/K\nT = 298.15  # K\ne = 1.6022e-19  # C\nNa = 6.022e23  # mol^-1\n# イオン濃度\nc_Ca = [0.001, 0.01]  # mol/L\nc_Cl = [0.002, 0.02]  # mol/L\nn_Ca = [1*Na, 10*Na] # /m^3\nn_Cl = [2*Na, 20*Na] # /m^3\n# イオン強度の計算\nfor i in range(len(c_Ca)):\n    I = 0.5 * (c_Ca[i] * 2**2 + c_Cl[i] * (-1)**2)\n    print(f\"イオン強度: {I:.3f} M\")\n    # デバイ半径の計算\n    nI = 0.5 * (n_Ca[i] * 2**2 + n_Cl[i] * (-1)**2)\n    lambda_D = 1 / np.sqrt(2 * e**2 / (epsilon_0 * epsilon_r * k * T) * nI) \n    print(f\"デバイ半径: {lambda_D:.3e} m\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nイオン強度: 0.003 M\nデバイ半径: 5.553e-09 m\nイオン強度: 0.030 M\nデバイ半径: 1.756e-09 m\n```\n:::\n:::\n\n\n:::\n\n### 3-3.\n\n$25^{\\circ}\\symup{C},\\ 5.0 \\times 10^{-3} \\ \\symup{M} \\ \\ce{KCl}$ 水溶液の**イオン強度**および**平均活量係数**を、**デバイ＝ヒュッケルの極限法則**を用いて求めよ。\n\n::: {.callout-note collapse=\"true\"}\n#### 理論\n\nイオン強度の式 (@eq-ion_strength) と平均活量計数の式 (@eq-debye_huckel) を使う計算問題\n\n$$\nA^\\ast = \\frac{1}{8\\pi}\\qty(\\frac{N_A}{1000})^{1/2}\\qty(\\frac{e^2}{\\epsilon_0\\epsilon_r kT})^{3/2}\n$$\n\nこの値おおよそ $1.2 \\ \\text{m}^{3/2} \\ \\text{mol}^{-1/2}$ である。詳しく計算させられることはないはずだ。\n\n:::\n\n::: {.callout-tip collapse=\"true\"}\n#### 解答\n\n$$\n\\begin{aligned}\nI &= \\frac{1}{2} \\left( c_{\\ce{K+}} z_{\\ce{K+}}^2 + c_{\\ce{Cl-}} z_{\\ce{Cl-}}^2 \\right) \\\\\n&= \\frac{1}{2} \\left( 5.0 \\times 10^{-3} \\times 1^2 + 5.0 \\times 10^{-3} \\times (-1)^2 \\right) \\\\\n&= 5.0 \\times 10^{-3} \\ \\text{M} \\\\\n\\gamma &= \\exp \\left( -A^\\ast z_{\\ce{K+}} z_{\\ce{Cl-}} \\sqrt{I} \\right) \\\\\n&= \\exp \\left( -1.2 \\times 1 \\times (-1) \\times \\sqrt{5.0 \\times 10^{-3}} \\right) \\\\\n&= 0.92\n\\end{aligned}\n$$\n\n::: {#2bef3a77 .cell execution_count=7}\n``` {.python .cell-code}\nimport numpy as np\n# 定数\nc_k = 5.0e-3  # mol/L\nc_cl = 5.0e-3  # mol/L\nz_k = 1\nz_cl = -1\n# デバイ＝ヒュッケルの極限法則\nA_star = 1.2  # m^3/2/mol^1/2\n# イオン強度の計算\nI = 0.5 * (c_k * z_k**2 + c_cl * z_cl**2)\nprint(f\"イオン強度: {I:.3f} M\")\n# 平均活量係数の計算\ngamma = np.exp(-A_star * z_k * z_cl * np.sqrt(I))\nprint(f\"平均活量係数: {gamma:.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nイオン強度: 0.005 M\n平均活量係数: 1.089\n```\n:::\n:::\n\n\n:::\n\n### 3-4.\n\n$25^{\\circ}\\symup{C},\\ 1.0 \\times 10^{-3} \\ \\symup{M} \\ \\ce{CaCl2}$ 水溶液の\\\n**イオン強度**および**平均活量係数**を、**デバイ＝ヒュッケルの極限法則**を用いて求めよ。\n\n::: {.callout-tip collapse=\"true\"}\n#### 解答\n\n$$\n\\begin{aligned}\nI &= \\frac{1}{2} \\left( c_{\\ce{Ca2+}} z_{\\ce{Ca2+}}^2 + c_{\\ce{Cl-}} z_{\\ce{Cl-}}^2 \\right) \\\\\n&= \\frac{1}{2} \\left( 1.0 \\times 10^{-3} \\times 2^2 + 2.0 \\times 10^{-3} \\times (-1)^2 \\right) \\\\\n&= 3.0 \\times 10^{-3} \\ \\text{M} \\\\\n\\gamma &= \\exp \\left( -A^\\ast z_{\\ce{Ca2+}} z_{\\ce{Cl-}} \\sqrt{I} \\right) \\\\\n&= \\exp \\left( -1.2 \\times 2 \\times (-1) \\times \\sqrt{3.0 \\times 10^{-3}} \\right) \\\\\n&= 0.88\n\\end{aligned}\n$$\n\n::: {#355b154e .cell execution_count=8}\n``` {.python .cell-code}\nimport numpy as np\n# 定数\nc_ca = 1.0e-3  # mol/L\nc_cl = 2 * 1.0e-3  # mol/L\nz_ca = 2\nz_cl = -1\n# デバイ＝ヒュッケルの極限法則\nA_star = 1.2  # m^3/2/mol^1/2\n# イオン強度の計算\nI = 0.5 * (c_ca * z_ca**2 + c_cl * z_cl**2)\nprint(f\"イオン強度: {I:.3f} M\")\n# 平均活量係数の計算\ngamma = np.exp(A_star * z_ca * z_cl * np.sqrt(I))\nprint(f\"平均活量係数: {gamma:.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nイオン強度: 0.003 M\n平均活量係数: 0.877\n```\n:::\n:::\n\n\n:::\n\n### 3-5.\n\n$25^{\\circ}\\symup{C}$ の水（比誘電率：78.54）に対し、定数部分を計算し、ボルン式を下記の形で表記せよ。\n\n$$\n\\Delta G_S^\\circ = -\\frac{z^2}{r_i\\ [\\mathrm{pm}]} \\times (\\text{定数})\\ \\left[\\mathrm{kJ\\ mol^{-1}}\\right]\n$$\n\n$$\n\\begin{aligned}\nN_A &= 6.022 \\times 10^{23}\\ [\\mathrm{mol}^{-1}] \\\\\ne &= 1.6022 \\times 10^{-19}\\ [\\mathrm{C}] \\\\\n\\varepsilon_0 &= 8.8542 \\times 10^{-12}\\ [\\mathrm{F\\ m^{-1}}]\n\\end{aligned}\n$$\n\n\n\n::: {.callout-tip collapse=\"true\"}\n##### 解答\n\n@sec-born_eq より、\n\n$$\n\\Delta G_S^\\circ = -\\frac{z^2}{r_i\\ [\\mathrm{pm}]} \\times (\\text{定数})\\ \\left[\\mathrm{kJ\\ mol^{-1}}\\right]\n$$\n\nなので、\n\n$$\n\\text{（定数）} = \\frac{N_A e^2}{8 \\pi \\varepsilon_0} \\times 10^9\\ \\left[\\frac{\\mathrm{pm}}{\\mathrm{m}}\\right] \\times 10^{-3}\\ \\left[\\frac{\\mathrm{kJ}}{\\mathrm{J}}\\right] \\times \\left(1 - \\frac{1}{\\varepsilon_r}\\right)\n= 6.86 \\times 10^4\n$$\n\n::: \n\n### 3-6.\n\n上記求めた式を用い、$\\ce{Cl-}$ および $\\ce{I-}$ における $\\Delta G_S^\\circ$ を計算してみよ。  \n$\\ce{Cl-}$ および $\\ce{I-}$ のイオン半径はそれぞれ 181 pm, 220 pm とする。\n\n::: {.callout-tip collapse=\"true\"}\n##### 解答\n\n$$\n\\begin{aligned}\n\\Delta G_S^\\circ(\\ce{Cl-}) &= -\\frac{1^2}{181} \\times 6.86 \\times 10^4 \\ \\mathrm{kJ\\ mol^{-1}} \\\\\n&= -379 \\ \\mathrm{kJ\\ mol^{-1}} \\\\\n\\Delta G_S^\\circ(\\ce{I-}) &= -\\frac{1^2}{220} \\times 6.86 \\times 10^4 \\ \\mathrm{kJ\\ mol^{-1}} \\\\\n&= -312 \\ \\mathrm{kJ\\ mol^{-1}}\n\\end{aligned}\n$$\n\n::: {#5d80e26e .cell execution_count=9}\n``` {.python .cell-code}\n# 定数\nr_cl = 181  # pm\nr_i = 220  # pm\n# ボルン式の計算\ndelta_G_S_circ_cl = -1 / r_cl * 6.86e4  # kJ/mol\ndelta_G_S_circ_i = -1 / r_i * 6.86e4  # kJ/mol\nprint(f\"ΔG_S^°(Cl-): {delta_G_S_circ_cl:.3f} kJ/mol\")\nprint(f\"ΔG_S^°(I-): {delta_G_S_circ_i:.3f} kJ/mol\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nΔG_S^°(Cl-): -379.006 kJ/mol\nΔG_S^°(I-): -311.818 kJ/mol\n```\n:::\n:::\n\n\n::: \n\n### 4-1.\n\nネルンストの式を導き出せ。\n\n::: {.callout-tip collapse=\"true\"}\n#### 解答\n\n$$\n\\ce{Ox^{z+}} + ne^- \\ce{<=> Red^{(z-n)+}}\n$$\n\n$$\n\\begin{aligned}\n\\mu_{\\ce{Ox}} &= \\mu_{\\ce{Ox}}^{O} + RT \\ln a_{\\ce{Ox}} + z_i F \\phi_{Liq} \\\\\n\\mu_{\\ce{Red}} &= \\mu_{\\ce{Red}}^{O} + RT \\ln a_{\\ce{Red}} + (z-n)F \\phi_{Liq} \\\\\n\\mu_{e^-} &= \\mu_{e^-}^{O} + RT \\ln a_{e^-} - F \\phi_{M}\n\\end{aligned}\n$$\n\nこれらを組み合わせて、\n\n$$\n\\begin{aligned}\n\\Delta \\phi &= \\frac{\\mu_{\\ce{Ox}} - \\mu_{\\ce{Red}} + n \\mu_{e^-}}{\\Delta n F} + \\frac{RT}{nF} \\ln \\frac{a_{\\ce{Ox}}}{a_{\\ce{Red}}} \\\\\n&= \\frac{\\Delta G}{\\Delta n F} + \\frac{RT}{nF} \\ln \\frac{a_{\\ce{Ox}}}{a_{\\ce{Red}}} \\\\\n&= E^O + \\frac{RT}{nF} \\ln \\frac{a_{\\ce{Ox}}}{a_{\\ce{Red}}}\n\\end{aligned}\n$$\n\nこれ以降はこの式一本で色々とやっていくだけ。\n\n::: \n\n### 4-2.\n\n以下の溶解反応における標準酸化還元電位（標準電位）vs SHE を標準生成ギブズエネルギー変化より求めよ\n\na.  \n$$\n\\mathrm{Zn} \\rightleftharpoons \\mathrm{Zn}^{2+} + 2e^-\n$$\n\nb.  \n$$\n\\mathrm{Al}^{3+} + 3e^- \\rightleftharpoons \\mathrm{Al}\n$$\n\n::: {.callout-tip collapse=\"true\"}\n##### 解答\n\nThis is an example of a callout with a title.\n::: \n\n# 過去問\n\n<!-- \n::: {.callout-note collapse=\"true\"}\n##### 理論\n\nThis is an example of a callout with a title.\n:::\n\n::: {.callout-tip collapse=\"true\"}\n##### 解答\n\nThis is an example of a callout with a title.\n::: \n-->\n\n## 2018年度（前半）\n\n### 問1\n\n1.  電気二重層は、正電荷の表面に固定吸着された陰イオン（または負電荷に吸着した陽イオン）からなる非常に薄い層（Stern-Helmholtz層）と、静電引力の中で拡散しつつ濃度分布が生じる層（拡散層あるいはGouy-Chapman層）の２つの層で構成される。\n\n2.  荷電粒子あるいは分子が電場（電界）中を移動する現象。\n\n3.  液体と固体が接している所に電圧をかけた場合に、液体が移動する現象。これにより生じる液体の流れを電気浸透流（でんきしんとうりゅう）という\n\n### 問2\n\n::: {.callout-note collapse=\"true\"}\n##### 理論\n\nフィックの法則の式が書ければ大体大丈夫。\n:::\n\n::: {.callout-tip collapse=\"true\"}\n##### 解答\n\n1.  Fickの第一法則は次の式の通り\n\n$$\nJ = -D \\dv{c}{x}\n$$\n\nここで拡散層の厚さが薄いと仮定して、\n\n$$\n\\begin{aligned}\n\\dv{c}{x} = \\dfrac{C}{d} = 1.0 \\ \\symup{mol\\ cm^{-3}} / 1 \\times 10^{-2} \\ \\symup{cm} \\\\\n= 1.0 \\times 10^{2} \\ \\symup{mol\\ cm^{-4}}\n\\end{aligned}\n$$\n\nこれに拡散係数を考えて、\n\n$$\nJ = 0.72 \\times 10^{-5} \\ \\symup{cm^2\\ s^{-1}} \\times 1.0 \\times 10^{2} \\ \\symup{mol\\ cm^{-4}} = 7.2 \\times 10^{-4} \\ \\symup{mol\\ cm^{-2} s^{-1}}\n$$\n\n電解電流密度なので、$z=2$ を考えて、\n\n::: {#f5418a98 .cell execution_count=10}\n``` {.python .cell-code}\n# 定数\nF = 96485  # C/mol\nJ = 7.2e-4  # mol/cm^2/s\n# 電流密度の計算\ncurrent_density = J * 2 * F  # A/cm^2\nprint(f\"電流密度: {current_density:.3e} A/cm^2\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n電流密度: 1.389e+02 A/cm^2\n```\n:::\n:::\n\n\n$$\nJ = 7.2 \\times 10^{-4} \\ \\symup{mol\\ cm^{-2} s^{-1}} \\times 2 \\times 96485 \\ \\symup{C/mol} = 1.4 \\times 10^{2} \\ \\symup{A\\ cm^{-2}}\n$$\n:::\n\n## 2018年度（後半）\n\n| 物質           | $\\Delta G^\\circ_f [\\mathrm{kJ \\cdot mol^{-1}}]$ |\n|-----------------|---------------|\n| $\\ce{H+}$       | 0.00          |\n| $\\ce{Zn^{2+}}$  | -147.06       |\n| $\\ce{Fe^{2+}}$  | -78.9         |\n| $\\ce{Al^{3+}}$  | -485          |\n| $\\ce{Cu^{2+}}$  | 65.49         |\n| $\\ce{PbCl2}$    | -314.1        |\n| $\\ce{Cl-}$      | -131.23       |\n| $\\ce{Na+}$      | -261.91       |\n| $\\ce{MnO2}$     | -465.14       |\n| $\\ce{H2O}$      | -237.13       |\n| $\\ce{Mn(OH)2}$  | -618.58       |\n| $\\ce{Zn(OH)2}$  | -555.07       |\n| $\\ce{OH-}$      | -157.24       |\n| $\\ce{CH3COOH}$  | -396.46       |\n\n: 標準生成ギブスエネルギー\n\n### 問1\n\n以下の問いに答えよ。\n\n温度は $25^{\\circ}\\symup{K}$（$298.15 \\symup{K}$）の標準温度とし、必要に応じてイオンの活量係数は 1 として良い。電位の基準は標準水素電極電位とする。ファラデー定数には $F = 9.65 \\times 10^4\\;\\mathrm{C \\cdot mol^{-1}}$ 気体定数には $R = 8.31\\;\\mathrm{J \\cdot K^{-1} \\cdot mol^{-1}}$ を用いよ。**計算過程も明記すること。**\\\n単位 \\[M\\] は $\\mathrm{mol/L}$ である。必要に応じ、表1の値を用いよ。\n\n---\n\n#### 1-1\n\n$\\ce{HCl}$、$\\ce{NaCl}$、$\\ce{CH3COONa}$ 水溶液の無限希釈モル導電率はそれぞれ\\\n426.3、126.4、91.0 \\[$\\mathrm{S \\cdot cm^2 \\cdot mol^{-1}}$\\] である。\\\n酢酸 $\\ce{CH3COOH}$ の無限希釈モル導電率を求めよ。\n\n#### 1-2\n\n0.02 M 酢酸水溶液の導電率は $2.31 \\times 10^{-4}\\;\\mathrm{S \\cdot cm^{-1}}$ だった。\\\n(1-1) の結果を用い、0.02 M における酢酸の電離度 $\\alpha$ と、酢酸の解離定数 $K$ を求めよ。\n\n#### 1-3\n\n$\\ce{CH3COO-}$ の標準生成ギブスエネルギーを求めよ。\n\n::: {.callout-note collapse=\"true\"}\n##### 理論\n\n1-1 では、 @eq-molar_conductivity を用いる。\n\n1-2 では、 @eq-dilution_law_alpha と @eq-dilution_law を用いる。ただし、導電率とモル伝導率の単位と換算について注意すること。\n\n:::\n\n::: {.callout-tip collapse=\"true\"}\n##### 解答\n\n1-1\n\n$\\ce{H+},\\ \\ce{Cl-},\\ \\ce{CH3COO-}$ のモル電気伝導率をそれぞれ $\\lambda_{\\ce{H+}},\\ \\lambda_{\\ce{Cl-}},\\ \\lambda_{\\ce{CH3COO-}}$ とすると、\n\n$$\n\\begin{aligned}\n\\lambda_{\\ce{H+}} + \\lambda_{\\ce{Cl-}} &= 426.3 \\\\\n\\lambda_{\\ce{Cl-}} + \\lambda_{\\ce{Na+}} &= 126.4 \\\\\n\\lambda_{\\ce{Na+}} + \\lambda_{\\ce{CH3COO-}} &= 91.0\n\\end{aligned}\n$$\n\nこれを解いて、\n\n$$\n\\lambda_{\\ce{H+}} + \\lambda_{\\ce{CH3COO-}} = 426.3 + 91.0 - 126.4 = 390.9 \\ \\mathrm{S \\cdot cm^2 \\cdot mol^{-1}}\n$$\n\n1-2\n\n$\\alpha = \\frac{\\lambda}{\\lambda^{\\infty}}$ となるので、まずは $\\lambda$ を求める。\n\n$$\n\\lambda = 2.31 \\times 10^{-4} \\ \\mathrm{S \\cdot cm^{-1}} / 0.02 \\ \\mathrm{M} = 1.155 \\times 10^{2} \\ \\mathrm{S \\cdot cm^2 \\cdot mol^{-1}}\n$$\n\n1-3\n\n$$\\Delta G_{\\ce{CH3COO-}} = \\Delta G_{\\ce{CH3COOH}} - \\Delta G_{\\ce{H+}} = -396.46 \\ \\mathrm{kJ \\cdot mol^{-1}}$$\n\n::: \n\n---\n\n### 問2\n\n::: {#f1bea79c .cell execution_count=11}\n``` {.python .cell-code}\nimport matplotlib.pyplot as plt\nimport matplotlib.patches as patches\n\n# 図の設定\nfig, ax = plt.subplots(figsize=(6, 6))\n\n# 領域の描画\nax.add_patch(patches.Polygon([[0, -0.763], [7, -0.763], [7, 1], [0, 1]], closed=True, facecolor='lightblue', edgecolor='black'))\nax.add_patch(patches.Polygon([[7, -0.763], [14, -1.25 + 0.059 * (14 - 14)], [14, 1], [7, 1]], closed=True, facecolor='lightgreen', edgecolor='black'))\nax.add_patch(patches.Polygon([[0, -2], [14, -2], [14, -1.25 + 0.059 * (14 - 14)], [7, -0.763], [0, -0.763]], closed=True, facecolor='lightgray', edgecolor='black'))\n\n# 境界線の描画\nax.plot([0, 7], [-0.763, -0.763], 'k', label='①')\nax.plot([7, 14], [-0.763, -1.25 + 0.059 * (14 - 14)], 'k', label='②')\n\n# ラベルの追加\nax.text(2, 0.2, '(A)', fontsize=14)\nax.text(10, 0.2, '(B)', fontsize=14)\nax.text(6, -1.6, '(C)', fontsize=14)\n\nax.text(3.5, -0.64, '①', fontsize=12, bbox=dict(boxstyle=\"circle\", fc=\"white\", ec=\"black\"))\nax.text(10.5, -0.9, '②', fontsize=12, bbox=dict(boxstyle=\"circle\", fc=\"white\", ec=\"black\"))\n\n# 軸ラベル\nax.set_xlabel('pH', fontsize=12)\nax.set_ylabel('E [V vs. SHE]', fontsize=12)\n\n# 軸の範囲\nax.set_xlim(0, 14)\nax.set_ylim(-2, 1)\n\n# グリッド\nax.grid(True)\n\nplt.title('Zn')\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](材料電気化学_files/figure-html/cell-12-output-1.png){}\n:::\n:::\n\n\n#### 2-1\n\n図1は、$\\ce{Zn^{2+}}$ の活量を1とした $\\ce{Zn}$ のプールベイ図である。(A)、(B)、(C) には、$\\ce{Zn^{2+}}$、$\\ce{Zn}$、$\\ce{Zn(OH)2}$ のいずれかが対応するか記述せよ。\n\n#### 2-2\n\n(A)と(C)の境界①が位置する平衡電極電位 $E$ を求めよ。\n\n#### 2-3\n\n(B)と(C)の境界②が示す平衡電極電位 $E$ を、$x = \\mathrm{pH}$ として $x$ の関数として求めよ。①との交点（$x$ の範囲）まで求める必要はない。\n\n#### 2-4\n\nアルカリマンガン電池は、電極材料として $\\ce{MnO2}$ および $\\ce{Zn}$、電解質として $\\ce{KOH}$ 水溶液を用いた電池である。放電後、正極および負極ともに水酸化物が生成された。\n\n正極反応、負極反応、および電池反応（全反応）を記述せよ。\n\n#### 2-5\n\n上記アルカリマンガン電池の開放電圧 $[V]$ を求めよ。必要に応じ、電解質の pH は 14 として良い。\n\n::: {.callout-note collapse=\"true\"}\n##### 理論\n\nこれは、[ネルンストの式](@sec-nerst_eq) を用いる問題。プールベイ図という年によっては講義資料に現れないグラフがあるが、要するにpH vs 電位のグラフである。\n\n次に、活量について混乱しかけたので、そのメモを置いておく。\n\nそもそも、活量というのは、実在溶液を理想溶液の形式で表すための補正係数つき濃度。定義式としては、\n\n$$\n\\mu_i = \\mu_i^0 + RT \\ln a_i\n$$\n\nとなる。ここで、$\\mu_i^0$ は標準化学ポテンシャル、$a_i$ は活量である。\n\nここで、$a_i = 1$ として良いという文言は数種類の状態について言及しているので注意すべきである。\n\n- 固体や純水、溶媒など。この理由は単純で、標準状態で考えているからだ。化学ポテンシャルやギブスエネルギーなどは、標準状態で測っていて、その状態の活量を1に定義しているんだ。\n- 溶液が無限希釈の状態。これは、溶液が薄いということで、溶液中のイオンの相互作用が小さくなるため、活量係数が1に近づく。**大事：活量自身が1になるわけではない**\n\n次に、この話を掘り進めてまとまった考えの一つも書いておく。\n\n$$ \\mu = \\mu^0 + RT \\ln a $$\n\nこの式の $RT \\ln a$ の部分だが、直接的なイメージが難しかったのだが、要するに $S=k\\ln W$ によってエントロピーを定義していて、そこからエネルギーなどとの関係性を考えている。エントロピーを粒子の居心地の悪さと考えると、その尺度は対数を使っているわけだ。同様にしてそのつながりて話を進める化学ポテンシャルも、要するに粒子の居心地の悪さを別の尺度で見ているだけで、その尺度は対数を使っているだけだ。\n\n2-4 は知識問題。\n\n:::\n\n::: {.callout-tip collapse=\"true\"}\n##### 解答\n\n2-1\n\n(A) は $\\ce{Zn^{2+}}$、(B) は $\\ce{Zn(OH)2}$、(C) は $\\ce{Zn}$ である。\n\n理由としては、(C)は電極の電位が低くても安定しているということは、完全に還元された形、 (A), (B) についてはpHから酸性か塩基性かを考えればいい。\n\n2-2\n\n$$\nE = E^O - \\frac{RT}{2F} \\ln \\frac{a_{\\ce{Zn^{2+}}}}{a_{\\ce{Zn}}}\n$$\n\nここで、\n\n$$E^O = - \\frac{\\Delta G^O}{nF} = - \\frac{147.06 \\times 10^3}{2 \\times 96485} = -0.763 \\ \\mathrm{V}$$ \n\nである。これが答えそのものだ。注意として、 $\\Delta G^O$ は、$\\ce{Zn^{2+} + 2e^- -> Zn}$ の反応である。 $\\Delta G^O_{\\text{Red}} - \\Delta G^O_{\\text{Ox}}$ なので、符合を間違えないように。\n\n一応活量は1として良いということなので、計算式は以下の通り。\n\n$$\n\\begin{aligned}\nE &= -0.763 - \\frac{8.31 \\times 298.15}{2 \\times 96485} \\ln \\frac{1}{1} \\\\\n&= -0.763 \\ \\mathrm{V}\n\\end{aligned}\n$$\n\n2-3\n\nネルンストの式を用いれば、\n\n$$\nE = E^O + \\frac{0.059}{2} \\ln \\frac{1}{a_{\\ce{OH-}}^2}\n$$\n\nとなる。ここで、反応式は\n\n$$\n\\ce{Zn(OH)2 + 2e^- -> Zn + 2OH^-}\n$$\n\nである。なので、 $\\Delta G^O = 2\\Delta G^O_{\\ce{OH-}} - \\Delta G^O_{\\ce{Zn(OH)2}} = 240.5 \\times 10^3 \\ \\mathrm{J/mol}$ となる。注意として、 $\\Delta G^O_{\\ce{OH-}}$ を忘れないようにしよう。\n\n$$\nE^O = - \\frac{\\Delta G^O}{nF} = - \\frac{240.5 \\times 10^3}{2 \\times 96485} = -1.246 \\ \\mathrm{V}\n$$ \n\n::: {#827abd6b .cell execution_count=12}\n``` {.python .cell-code}\n# 定数\nF = 96485  # C/mol\nR = 8.31  # J/K/mol\nT = 298.15  # K\n\n# 計算\nE_O = -240.5e3 / (2 * F)\nprint(f\"E^O: {E_O:.3f} V\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nE^O: -1.246 V\n```\n:::\n:::\n\n\nである。\n\n$$\nE = -1.25 + 0.059  (14 - x) = -0.336 - 0.059x\n$$\n\n2-4\n\n実際には、\n\n- 正極：$\\ce{MnO2 + H2O + e^- -> MnOOH + OH^-}$\n- 負極：$\\ce{Zn + 2OH^- -> Zn(OH)2 + 2e^-}$\n- 全反応：$\\boxed{\\ce{MnO2 + Zn + H2O -> MnOOH + Zn(OH)2}}$\n\nただ、2-5の問題を解くためにはこうせざるを得ない。\n\n- 正極：$\\ce{MnO2 + 2H2O + 2e^- -> Mn(OH)2 + 2OH^-}$\n- 負極：$\\ce{Zn + 2OH^- -> Zn(OH)2 + 2e^-}$\n- 全反応：$\\ce{MnO2 + Zn + 2H2O -> Mn(OH)2 + Zn(OH)2}$\n\n2-5\n\n$$\n\\Delta G^O = -555.07 - 618.58 + 2 * 237.13 + 465.14 = -234.25 \\ \\mathrm{kJ/mol}\n$$\n\n::: {#9c9cf308 .cell execution_count=13}\n``` {.python .cell-code}\nG = -555.07 - 618.58 + 2 * 237.13 + 465.14\nprint(f\"G: {G:.3f} J/mol\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nG: -234.250 J/mol\n```\n:::\n:::\n\n\n$$\nE = - \\frac{\\Delta G^O}{nF} = 1.214 \\ \\mathrm{V}\n$$\n\n::: {#1cc37eef .cell execution_count=14}\n``` {.python .cell-code}\nE = -234.25e3 / (2 * F)\nprint(f\"E: {E:.3f} V\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nE: -1.214 V\n```\n:::\n:::\n\n\n[文献値](https://www.jstage.jst.go.jp/article/itej1978/33/5/33_5_395/_pdf/-char/ja)は1.7Vということなので、結構小さい値が出てくる。\n\n::: \n\n---\n\n### 問3\n\n#### 3-1\n\n以下の反応における標準酸化還元電位をそれぞれ求めよ。\n\na) $\\ce{Al^{3+} + 3e^- <=> Al}$\n\nb) $\\ce{Fe <=> Fe^{2+} + 2e^-}$\n\nc) $\\ce{Cu^{2+} + 2e^- <=> Cu}$\n\nd) $\\ce{Pb + 2Cl^- <=> PbCl2 + 2e^-}$\n\ne) $\\ce{Na <=> Na^+ + e^-}$\n\n\n#### 3-2\n\nダニエル電池の電池反応を記述せよ。  \nまた、液相間電位を $0\\ \\mathrm{V}$ とし、$\\ce{Zn^{2+}}$ の活量を $0.05$、$\\ce{Cu^{2+}}$ の活量を $0.002$ とした際の起電力を求めよ。\n\n::: {.callout-note collapse=\"true\"}\n##### 理論\n\n3-1はただの計算問題。3-2はちょっと面倒な計算問題。\n\n:::\n\n::: {.callout-tip collapse=\"true\"}\n##### 解答\n\n3-1\n\na) $\\ce{Al^{3+} + 3e^- <=> Al}$\n\n- $\\Delta G^\\circ (\\ce{Al^{3+}}) = -485\\ \\mathrm{kJ/mol}$\n- $n = 3$\n\n$$\nE^\\circ = -\\frac{-485000}{3 \\times 96485} = \\boxed{1.675\\ \\mathrm{V}}\n$$\n\nb) $\\ce{Fe <=> Fe^{2+} + 2e^-}$\n\n- $\\Delta G^\\circ (\\ce{Fe^{2+}}) = -78.9\\ \\mathrm{kJ/mol}$\n- $n = 2$\n\n$$\nE^\\circ = -\\frac{-78900}{2 \\times 96485} = \\boxed{0.409\\ \\mathrm{V}}\n$$\n\nc) $\\ce{Cu^{2+} + 2e^- <=> Cu}$\n\n- $\\Delta G^\\circ (\\ce{Cu^{2+}}) = 65.49\\ \\mathrm{kJ/mol}$\n- $n = 2$\n\n$$\nE^\\circ = -\\frac{65490}{2 \\times 96485} = \\boxed{-0.339\\ \\mathrm{V}}\n$$\n\nd) $\\ce{Pb + 2Cl^- <=> PbCl2 + 2e^-}$\n\n- $\\Delta G^\\circ (\\ce{PbCl2}) = -314.1\\ \\mathrm{kJ/mol}$\n- $\\Delta G^\\circ (\\ce{Cl^-}) = -131.23\\ \\mathrm{kJ/mol}$\n- $n = 2$\n\n$$\n\\Delta G^\\circ_{\\text{rxn}} = -314.1 - 2 \\times (-131.23) = -314.1 + 262.46 = -51.64\\ \\mathrm{kJ/mol}\n$$\n\n$$\nE^\\circ = -\\frac{-51640}{2 \\times 96485} = \\boxed{0.267\\ \\mathrm{V}}\n$$\n\ne) $\\ce{Na <=> Na^+ + e^-}$\n\n- $\\Delta G^\\circ (\\ce{Na^+}) = -261.91\\ \\mathrm{kJ/mol}$\n- $n = 1$\n\n$$\nE^\\circ = -\\frac{-261910}{1 \\times 96485} = \\boxed{2.715\\ \\mathrm{V}}\n$$\n\n---\n\n3-2\n\n$$\n\\ce{Zn + Cu^{2+} -> Zn^{2+} + Cu}\n$$\n\nこれは、Znが酸化、Cuが還元される反応。\n\n- $\\ce{Zn^{2+} + 2e^- <=> Zn}$  \n  - $\\Delta G^\\circ = -147.06\\ \\mathrm{kJ/mol}$  \n  - $E^\\circ_{\\ce{Zn}} = -\\frac{-147060}{2 \\times 96485} = 0.762\\ \\mathrm{V}$\n\n- $\\ce{Cu^{2+} + 2e^- <=> Cu}$  \n  - $E^\\circ_{\\ce{Cu}} = -0.339\\ \\mathrm{V}$\n\nネルンスト式で計算：\n\n$$\nE_{\\text{cell}} = E^\\circ_{\\ce{Cu}} - E^\\circ_{\\ce{Zn}} + \\frac{RT}{nF} \\ln \\left( \\frac{a_{\\ce{Cu^{2+}}}}{a_{\\ce{Zn^{2+}}}} \\right)\n$$\n\n常温（$25^\\circ\\mathrm{C}$）なら $ \\frac{RT}{F} \\approx 0.025693\\ \\mathrm{V} $、よって：\n\n$$\n\\begin{aligned}\nE_{\\text{cell}} &= -0.339 - 0.762 + \\frac{0.059}{2} \\log_{10} \\left( \\frac{0.002}{0.05} \\right) \\\\\n&= -1.101 + 0.0295 \\times \\log_{10}(0.04) \\\\\n&= -1.101 + 0.0295 \\times (-1.398) \\\\\n&= -1.101 - 0.0413 \\\\\n&= \\boxed{-1.142\\ \\mathrm{V}}\n\\end{aligned}\n$$\n\n::: {#39044bee .cell execution_count=15}\n``` {.python .cell-code}\nimport numpy as np\n\nE_cell = -0.339 - 0.762 + 0.0295 * np.log10(0.002 / 0.05)\nprint(f\"E_cell: {E_cell:.3f} V\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nE_cell: -1.142 V\n```\n:::\n:::\n\n\n::: \n\n---\n\n### 問4\n\n以下の (A)〜(G) の内 2 つを選び、それぞれ 1〜2 行程度で簡単に説明せよ。\n\nA. アノード反応  \nB. コールラウシュの平方根則  \nC. ルイスの塩基性  \nD. 電気伝導度滴定  \nE. 光電気化学  \nF. ボルタ電位差  \nG. 水素過電圧  \n\n**解答例**  \nX. 電池：化学エネルギーを電気エネルギーとして取り出す装置\n\n::: {.callout-tip collapse=\"true\"}\n##### 解答\n\n| 用語 | 説明 |\n|------|------|\n| アノード | 酸化反応が起こる（陽極）。電子を放出して電極を通じて外部回路に流す。|\n| コールラウシュの平方根則 | 電解質の電気伝導度は、希薄溶液において濃度の平方根に比例して減少する（特に強電解質で有効）。|\n| ルイスの塩基性 | 電子対を供与できる物質。アンモニアなどがその例。|\n| 電気伝導度滴定 | 導電率の変化から中和点などを判断する滴定法。|\n| 光電気化学 | 光エネルギーによって起こる電気化学反応を扱う。太陽光水分解など。|\n| ボルタ電位差 | 異種金属電極間に生じる電位差で、電子の移動しやすさの違いに起因する。|\n| 水素過電圧 | 水素発生に必要な理論電位よりも高い電圧。電極材に依存する。|\n\n::: \n\n",
    "supporting": [
      "材料電気化学_files"
    ],
    "filters": [],
    "includes": {}
  }
}